package sources

// englishSources contains all English-language crypto news RSS feeds
// organized by category and tier
var englishSources = []FeedSource{
	// ============================================================================
	// TIER 1: Major News Outlets (Must-Have Sources)
	// ============================================================================
	{
		Key:        "coindesk",
		Name:       "CoinDesk",
		RSSURL:     "https://www.coindesk.com/arc/outboundfeeds/rss/",
		WebsiteURL: "https://www.coindesk.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"tier1", "news", "market"},
		IsEnabled:  true,
	},
	{
		Key:        "cointelegraph",
		Name:       "Cointelegraph",
		RSSURL:     "https://cointelegraph.com/rss",
		WebsiteURL: "https://cointelegraph.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"tier1", "news", "market"},
		IsEnabled:  true,
	},
	{
		Key:        "theblock",
		Name:       "The Block",
		RSSURL:     "https://www.theblock.co/rss.xml",
		WebsiteURL: "https://www.theblock.co",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"tier1", "news", "institutional"},
		IsEnabled:  true,
	},
	{
		Key:        "decrypt",
		Name:       "Decrypt",
		RSSURL:     "https://decrypt.co/feed",
		WebsiteURL: "https://decrypt.co",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"tier1", "news", "web3"},
		IsEnabled:  true,
	},
	{
		Key:        "bitcoinmagazine",
		Name:       "Bitcoin Magazine",
		RSSURL:     "https://bitcoinmagazine.com/.rss/full/",
		WebsiteURL: "https://bitcoinmagazine.com",
		Category:   "bitcoin",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"tier1", "bitcoin", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "blockworks",
		Name:       "Blockworks",
		RSSURL:     "https://blockworks.co/feed",
		WebsiteURL: "https://blockworks.co",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"tier1", "institutional", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// BITCOIN FOCUSED
	// ============================================================================
	{
		Key:        "bitcoinist",
		Name:       "Bitcoinist",
		RSSURL:     "https://bitcoinist.com/feed/",
		WebsiteURL: "https://bitcoinist.com",
		Category:   "bitcoin",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"bitcoin", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "btctimes",
		Name:       "BTC Times",
		RSSURL:     "https://www.btctimes.com/feed",
		WebsiteURL: "https://www.btctimes.com",
		Category:   "bitcoin",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"bitcoin", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "bitcoinoptech",
		Name:       "Bitcoin Optech",
		RSSURL:     "https://bitcoinops.org/feed.xml",
		WebsiteURL: "https://bitcoinops.org",
		Category:   "bitcoin",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"bitcoin", "technical", "development"},
		IsEnabled:  true,
	},

	// ============================================================================
	// DEFI
	// ============================================================================
	{
		Key:        "thedefiant",
		Name:       "The Defiant",
		RSSURL:     "https://thedefiant.io/feed",
		WebsiteURL: "https://thedefiant.io",
		Category:   "defi",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"defi", "news", "analysis"},
		IsEnabled:  true,
	},
	{
		Key:        "defiprime",
		Name:       "DeFi Prime",
		RSSURL:     "https://defiprime.com/feed.xml",
		WebsiteURL: "https://defiprime.com",
		Category:   "defi",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"defi", "directory"},
		IsEnabled:  true,
	},

	// ============================================================================
	// RESEARCH & ANALYSIS
	// ============================================================================
	{
		Key:        "glassnode",
		Name:       "Glassnode Insights",
		RSSURL:     "https://insights.glassnode.com/rss/",
		WebsiteURL: "https://glassnode.com",
		Category:   "research",
		Language:   "en",
		Region:     "global",
		IsPremium:  true,
		Tags:       []string{"research", "on-chain", "analytics"},
		IsEnabled:  true,
	},
	{
		Key:        "chainalysis",
		Name:       "Chainalysis Blog",
		RSSURL:     "https://blog.chainalysis.com/feed/",
		WebsiteURL: "https://www.chainalysis.com",
		Category:   "research",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"research", "compliance", "analytics"},
		IsEnabled:  true,
	},
	{
		Key:        "coinmetrics",
		Name:       "Coin Metrics",
		RSSURL:     "https://coinmetrics.io/feed/",
		WebsiteURL: "https://coinmetrics.io",
		Category:   "research",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"research", "data", "metrics"},
		IsEnabled:  true,
	},

	// ============================================================================
	// ETHEREUM & LAYER 2
	// ============================================================================
	{
		Key:        "ethresearch",
		Name:       "Ethereum Research",
		RSSURL:     "https://ethresear.ch/posts.rss",
		WebsiteURL: "https://ethresear.ch",
		Category:   "ethereum",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"ethereum", "research", "development"},
		IsEnabled:  true,
	},
	{
		Key:        "ethfoundation",
		Name:       "Ethereum Foundation Blog",
		RSSURL:     "https://blog.ethereum.org/feed.xml",
		WebsiteURL: "https://blog.ethereum.org",
		Category:   "ethereum",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"ethereum", "official", "development"},
		IsEnabled:  true,
	},
	{
		Key:        "zksync",
		Name:       "zkSync Blog",
		RSSURL:     "https://blog.matter-labs.io/feed",
		WebsiteURL: "https://zksync.io",
		Category:   "layer2",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"layer2", "zk", "rollup"},
		IsEnabled:  true,
	},
	{
		Key:        "starknet",
		Name:       "StarkNet Blog",
		RSSURL:     "https://medium.com/feed/starkware",
		WebsiteURL: "https://starknet.io",
		Category:   "layer2",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"layer2", "zk", "rollup"},
		IsEnabled:  true,
	},

	// ============================================================================
	// TRADING & MARKETS
	// ============================================================================
	{
		Key:        "ambcrypto",
		Name:       "AMBCrypto",
		RSSURL:     "https://ambcrypto.com/feed/",
		WebsiteURL: "https://ambcrypto.com",
		Category:   "trading",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"trading", "analysis", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "beincrypto",
		Name:       "BeInCrypto",
		RSSURL:     "https://beincrypto.com/feed/",
		WebsiteURL: "https://beincrypto.com",
		Category:   "trading",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"trading", "news", "analysis"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptobriefing",
		Name:       "Crypto Briefing",
		RSSURL:     "https://cryptobriefing.com/feed/",
		WebsiteURL: "https://cryptobriefing.com",
		Category:   "trading",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"trading", "defi", "research"},
		IsEnabled:  true,
	},
	{
		Key:        "coingape",
		Name:       "CoinGape",
		RSSURL:     "https://coingape.com/feed/",
		WebsiteURL: "https://coingape.com",
		Category:   "trading",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"trading", "news", "analysis"},
		IsEnabled:  true,
	},

	// ============================================================================
	// NFT
	// ============================================================================
	{
		Key:        "nftevening",
		Name:       "NFT Evening",
		RSSURL:     "https://nftevening.com/feed/",
		WebsiteURL: "https://nftevening.com",
		Category:   "nft",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"nft", "news", "drops"},
		IsEnabled:  true,
	},
	{
		Key:        "nftplazas",
		Name:       "NFT Plazas",
		RSSURL:     "https://nftplazas.com/feed/",
		WebsiteURL: "https://nftplazas.com",
		Category:   "nft",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"nft", "metaverse", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "nftculture",
		Name:       "NFT Culture",
		RSSURL:     "https://www.nftculture.com/feed/",
		WebsiteURL: "https://www.nftculture.com",
		Category:   "nft",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"nft", "art", "culture"},
		IsEnabled:  true,
	},

	// ============================================================================
	// GENERAL NEWS
	// ============================================================================
	{
		Key:        "cryptoslate",
		Name:       "CryptoSlate",
		RSSURL:     "https://cryptoslate.com/feed/",
		WebsiteURL: "https://cryptoslate.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "market", "research"},
		IsEnabled:  true,
	},
	{
		Key:        "newsbtc",
		Name:       "NewsBTC",
		RSSURL:     "https://www.newsbtc.com/feed/",
		WebsiteURL: "https://www.newsbtc.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "bitcoin", "trading"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptopotato",
		Name:       "CryptoPotato",
		RSSURL:     "https://cryptopotato.com/feed/",
		WebsiteURL: "https://cryptopotato.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "market", "education"},
		IsEnabled:  true,
	},
	{
		Key:        "dailyhodl",
		Name:       "The Daily Hodl",
		RSSURL:     "https://dailyhodl.com/feed/",
		WebsiteURL: "https://dailyhodl.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "market", "altcoins"},
		IsEnabled:  true,
	},
	{
		Key:        "u_today",
		Name:       "U.Today",
		RSSURL:     "https://u.today/rss",
		WebsiteURL: "https://u.today",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "market", "altcoins"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptonews",
		Name:       "Crypto.news",
		RSSURL:     "https://crypto.news/feed/",
		WebsiteURL: "https://crypto.news",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "market"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptodaily",
		Name:       "Crypto Daily",
		RSSURL:     "https://cryptodaily.co.uk/feed",
		WebsiteURL: "https://cryptodaily.co.uk",
		Category:   "general",
		Language:   "en",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"news", "uk"},
		IsEnabled:  true,
	},
	{
		Key:        "coinpedia",
		Name:       "Coinpedia",
		RSSURL:     "https://coinpedia.org/feed/",
		WebsiteURL: "https://coinpedia.org",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "market"},
		IsEnabled:  true,
	},
	{
		Key:        "coinspeaker",
		Name:       "Coinspeaker",
		RSSURL:     "https://www.coinspeaker.com/feed/",
		WebsiteURL: "https://www.coinspeaker.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "fintech"},
		IsEnabled:  true,
	},
	{
		Key:        "coinjournal",
		Name:       "CoinJournal",
		RSSURL:     "https://coinjournal.net/feed/",
		WebsiteURL: "https://coinjournal.net",
		Category:   "general",
		Language:   "en",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"news", "market"},
		IsEnabled:  true,
	},
	{
		Key:        "blockonomi",
		Name:       "Blockonomi",
		RSSURL:     "https://blockonomi.com/feed/",
		WebsiteURL: "https://blockonomi.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "guides"},
		IsEnabled:  true,
	},
	{
		Key:        "zycrypto",
		Name:       "ZyCrypto",
		RSSURL:     "https://zycrypto.com/feed/",
		WebsiteURL: "https://zycrypto.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "market"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptomode",
		Name:       "CryptoMode",
		RSSURL:     "https://cryptomode.com/feed/",
		WebsiteURL: "https://cryptomode.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "analysis"},
		IsEnabled:  true,
	},
	{
		Key:        "nulltx",
		Name:       "NullTX",
		RSSURL:     "https://nulltx.com/feed/",
		WebsiteURL: "https://nulltx.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "technology"},
		IsEnabled:  true,
	},

	// ============================================================================
	// INSTITUTIONAL
	// ============================================================================
	{
		Key:        "kraken_blog",
		Name:       "Kraken Blog",
		RSSURL:     "https://blog.kraken.com/feed/",
		WebsiteURL: "https://blog.kraken.com",
		Category:   "institutional",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"institutional", "exchange", "official"},
		IsEnabled:  true,
	},

	// ============================================================================
	// MINING
	// ============================================================================
	{
		Key:        "hashrateindex",
		Name:       "Hashrate Index Blog",
		RSSURL:     "https://hashrateindex.com/blog/feed",
		WebsiteURL: "https://hashrateindex.com",
		Category:   "mining",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"mining", "data", "analysis"},
		IsEnabled:  true,
	},

	// ============================================================================
	// ALTCOINS
	// ============================================================================
	{
		Key:        "avalanche",
		Name:       "Avalanche Blog",
		RSSURL:     "https://medium.com/feed/avalancheavax",
		WebsiteURL: "https://www.avax.network",
		Category:   "altcoins",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"avalanche", "altcoins", "official"},
		IsEnabled:  true,
	},
	{
		Key:        "chainlink",
		Name:       "Chainlink Blog",
		RSSURL:     "https://blog.chain.link/feed/",
		WebsiteURL: "https://chain.link",
		Category:   "altcoins",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"chainlink", "oracle", "defi"},
		IsEnabled:  true,
	},

	// ============================================================================
	// SECURITY
	// ============================================================================
	{
		Key:        "slowmist",
		Name:       "SlowMist Blog",
		RSSURL:     "https://slowmist.medium.com/feed",
		WebsiteURL: "https://slowmist.com",
		Category:   "security",
		Language:   "en",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"security", "audit", "research"},
		IsEnabled:  true,
	},
	{
		Key:        "trailofbits",
		Name:       "Trail of Bits Blog",
		RSSURL:     "https://blog.trailofbits.com/feed/",
		WebsiteURL: "https://www.trailofbits.com",
		Category:   "security",
		Language:   "en",
		Region:     "na",
		IsPremium:  false,
		Tags:       []string{"security", "audit", "research"},
		IsEnabled:  true,
	},
	{
		Key:        "peckshield",
		Name:       "PeckShield Blog",
		RSSURL:     "https://peckshield.medium.com/feed",
		WebsiteURL: "https://peckshield.com",
		Category:   "security",
		Language:   "en",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"security", "audit", "alerts"},
		IsEnabled:  true,
	},

	// ============================================================================
	// GAMING & METAVERSE
	// ============================================================================
	{
		Key:        "gamedao",
		Name:       "GameDAO Blog",
		RSSURL:     "https://blog.gamedao.co/feed/",
		WebsiteURL: "https://gamedao.co",
		Category:   "gaming",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"gaming", "dao"},
		IsEnabled:  true,
	},
	{
		Key:        "sandbox",
		Name:       "The Sandbox Blog",
		RSSURL:     "https://medium.com/feed/sandbox-game",
		WebsiteURL: "https://www.sandbox.game",
		Category:   "gaming",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"metaverse", "gaming", "nft"},
		IsEnabled:  true,
	},

	// ============================================================================
	// REGULATION & LEGAL
	// ============================================================================
	{
		Key:        "coincenter",
		Name:       "Coin Center",
		RSSURL:     "https://www.coincenter.org/feed/",
		WebsiteURL: "https://www.coincenter.org",
		Category:   "regulation",
		Language:   "en",
		Region:     "na",
		IsPremium:  false,
		Tags:       []string{"regulation", "policy", "advocacy"},
		IsEnabled:  true,
	},

	// ============================================================================
	// ADDITIONAL SOURCES
	// ============================================================================
	{
		Key:        "coincu",
		Name:       "Coincu News",
		RSSURL:     "https://news.coincu.com/feed/",
		WebsiteURL: "https://news.coincu.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "market"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptoninjas",
		Name:       "CryptoNinjas",
		RSSURL:     "https://www.cryptoninjas.net/feed/",
		WebsiteURL: "https://www.cryptoninjas.net",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "technology"},
		IsEnabled:  true,
	},
	{
		Key:        "trustnodes",
		Name:       "Trustnodes",
		RSSURL:     "https://www.trustnodes.com/feed",
		WebsiteURL: "https://www.trustnodes.com",
		Category:   "general",
		Language:   "en",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"news", "analysis"},
		IsEnabled:  true,
	},
	{
		Key:        "cointelegraph_magazine",
		Name:       "Cointelegraph Magazine",
		RSSURL:     "https://cointelegraph.com/magazine/feed",
		WebsiteURL: "https://cointelegraph.com/magazine",
		Category:   "research",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"magazine", "longform"},
		IsEnabled:  true,
	},
	{
		Key:        "protos",
		Name:       "Protos",
		RSSURL:     "https://protos.com/feed/",
		WebsiteURL: "https://protos.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "investigation"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptonewsz",
		Name:       "CryptoNewsZ",
		RSSURL:     "https://www.cryptonewsz.com/feed/",
		WebsiteURL: "https://www.cryptonewsz.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "market"},
		IsEnabled:  true,
	},
	{
		Key:        "coinedition",
		Name:       "Coin Edition",
		RSSURL:     "https://coinedition.com/feed/",
		WebsiteURL: "https://coinedition.com",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "market"},
		IsEnabled:  true,
	},
	{
		Key:        "watcher_guru",
		Name:       "Watcher Guru",
		RSSURL:     "https://watcher.guru/news/feed",
		WebsiteURL: "https://watcher.guru",
		Category:   "general",
		Language:   "en",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"news", "alerts"},
		IsEnabled:  true,
	},
}
