package sources

// internationalSources contains all non-English crypto news RSS feeds
// organized by language and region
var internationalSources = []FeedSource{
	// ============================================================================
	// KOREAN (ko) - South Korea
	// ============================================================================
	{
		Key:        "blockmedia",
		Name:       "Block Media",
		RSSURL:     "https://www.blockmedia.co.kr/feed/",
		WebsiteURL: "https://www.blockmedia.co.kr",
		Category:   "general",
		Language:   "ko",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"korea", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "coindeskkorea",
		Name:       "CoinDesk Korea",
		RSSURL:     "https://www.coindeskkorea.com/feed/",
		WebsiteURL: "https://www.coindeskkorea.com",
		Category:   "general",
		Language:   "ko",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"korea", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "tokenpost_kr",
		Name:       "TokenPost Korea",
		RSSURL:     "https://www.tokenpost.kr/feed",
		WebsiteURL: "https://www.tokenpost.kr",
		Category:   "general",
		Language:   "ko",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"korea", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "blockinpress",
		Name:       "Blockinpress",
		RSSURL:     "https://blockinpress.com/feed/",
		WebsiteURL: "https://blockinpress.com",
		Category:   "general",
		Language:   "ko",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"korea", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "decenter",
		Name:       "Decenter",
		RSSURL:     "https://decenter.kr/rss/allArticle.xml",
		WebsiteURL: "https://decenter.kr",
		Category:   "general",
		Language:   "ko",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"korea", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "coinreaders",
		Name:       "CoinReaders",
		RSSURL:     "https://www.coinreaders.com/rss/allArticle.xml",
		WebsiteURL: "https://www.coinreaders.com",
		Category:   "general",
		Language:   "ko",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"korea", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "thebchain",
		Name:       "The Bchain",
		RSSURL:     "https://www.thebchain.co.kr/rss/allArticle.xml",
		WebsiteURL: "https://www.thebchain.co.kr",
		Category:   "general",
		Language:   "ko",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"korea", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "coindeskkorea_defi",
		Name:       "CoinDesk Korea DeFi",
		RSSURL:     "https://www.coindeskkorea.com/news/articleList.html?sc_area=A&view_type=rss",
		WebsiteURL: "https://www.coindeskkorea.com",
		Category:   "defi",
		Language:   "ko",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"korea", "defi"},
		IsEnabled:  true,
	},
	{
		Key:        "newsway_blockchain",
		Name:       "Newsway Blockchain",
		RSSURL:     "https://www.newsway.co.kr/rss/allArticle.xml",
		WebsiteURL: "https://www.newsway.co.kr",
		Category:   "general",
		Language:   "ko",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"korea", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "hankyung_blockchain",
		Name:       "Hankyung Blockchain",
		RSSURL:     "https://www.hankyung.com/feed/blockchain",
		WebsiteURL: "https://www.hankyung.com/blockchain",
		Category:   "general",
		Language:   "ko",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"korea", "mainstream"},
		IsEnabled:  true,
	},

	// ============================================================================
	// CHINESE (zh) - China/Taiwan/Hong Kong
	// ============================================================================
	{
		Key:        "8btc",
		Name:       "8BTC (Babbitt)",
		RSSURL:     "https://www.8btc.com/feed",
		WebsiteURL: "https://www.8btc.com",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"china", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "odaily",
		Name:       "Odaily",
		RSSURL:     "https://www.odaily.news/rss",
		WebsiteURL: "https://www.odaily.news",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"china", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "panews",
		Name:       "PANews",
		RSSURL:     "https://www.panewslab.com/rss",
		WebsiteURL: "https://www.panewslab.com",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"china", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "chaincatcher",
		Name:       "ChainCatcher",
		RSSURL:     "https://www.chaincatcher.com/rss",
		WebsiteURL: "https://www.chaincatcher.com",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"china", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "foresightnews",
		Name:       "Foresight News",
		RSSURL:     "https://foresightnews.pro/feed",
		WebsiteURL: "https://foresightnews.pro",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"china", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "techflowpost",
		Name:       "TechFlow",
		RSSURL:     "https://www.techflowpost.com/rss",
		WebsiteURL: "https://www.techflowpost.com",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"china", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "jinse",
		Name:       "Jinse Finance",
		RSSURL:     "https://www.jinse.com/rss",
		WebsiteURL: "https://www.jinse.com",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"china", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "blockbeats",
		Name:       "BlockBeats",
		RSSURL:     "https://www.theblockbeats.info/rss",
		WebsiteURL: "https://www.theblockbeats.info",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"china", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "blocktempo_zh",
		Name:       "BlockTempo Chinese",
		RSSURL:     "https://www.blocktempo.com/feed/",
		WebsiteURL: "https://www.blocktempo.com",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"taiwan", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "abmedia",
		Name:       "ABMedia",
		RSSURL:     "https://abmedia.io/feed/",
		WebsiteURL: "https://abmedia.io",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"taiwan", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "zombit",
		Name:       "Zombit",
		RSSURL:     "https://zombit.info/feed/",
		WebsiteURL: "https://zombit.info",
		Category:   "general",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"taiwan", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "wublock",
		Name:       "Wu Blockchain",
		RSSURL:     "https://wublock.substack.com/feed",
		WebsiteURL: "https://wublock.substack.com",
		Category:   "research",
		Language:   "zh",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"china", "research", "mining"},
		IsEnabled:  true,
	},

	// ============================================================================
	// JAPANESE (ja) - Japan
	// ============================================================================
	{
		Key:        "coinpost",
		Name:       "CoinPost",
		RSSURL:     "https://coinpost.jp/rss",
		WebsiteURL: "https://coinpost.jp",
		Category:   "general",
		Language:   "ja",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"japan", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "coindeskjapan",
		Name:       "CoinDesk Japan",
		RSSURL:     "https://www.coindeskjapan.com/feed/",
		WebsiteURL: "https://www.coindeskjapan.com",
		Category:   "general",
		Language:   "ja",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"japan", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "cointelegraph_ja",
		Name:       "Cointelegraph Japan",
		RSSURL:     "https://jp.cointelegraph.com/rss",
		WebsiteURL: "https://jp.cointelegraph.com",
		Category:   "general",
		Language:   "ja",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"japan", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "btcnews_ja",
		Name:       "Bitcoin News Japan",
		RSSURL:     "https://btcnews.jp/feed/",
		WebsiteURL: "https://btcnews.jp",
		Category:   "bitcoin",
		Language:   "ja",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"japan", "bitcoin"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptact",
		Name:       "Cryptact Blog",
		RSSURL:     "https://www.cryptact.com/blog/feed",
		WebsiteURL: "https://www.cryptact.com",
		Category:   "general",
		Language:   "ja",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"japan", "tax", "tools"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptotimes_ja",
		Name:       "Crypto Times Japan",
		RSSURL:     "https://crypto-times.jp/feed/",
		WebsiteURL: "https://crypto-times.jp",
		Category:   "general",
		Language:   "ja",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"japan", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "coinchoice",
		Name:       "CoinChoice",
		RSSURL:     "https://coinchoice.net/feed/",
		WebsiteURL: "https://coinchoice.net",
		Category:   "general",
		Language:   "ja",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"japan", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// SPANISH (es) - Spain & Latin America
	// ============================================================================
	{
		Key:        "cointelegraph_es",
		Name:       "Cointelegraph en Espanol",
		RSSURL:     "https://es.cointelegraph.com/rss",
		WebsiteURL: "https://es.cointelegraph.com",
		Category:   "general",
		Language:   "es",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"spanish", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "diariobitcoin",
		Name:       "Diario Bitcoin",
		RSSURL:     "https://www.diariobitcoin.com/feed/",
		WebsiteURL: "https://www.diariobitcoin.com",
		Category:   "general",
		Language:   "es",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"spanish", "news", "venezuela"},
		IsEnabled:  true,
	},
	{
		Key:        "criptonoticias",
		Name:       "CriptoNoticias",
		RSSURL:     "https://www.criptonoticias.com/feed/",
		WebsiteURL: "https://www.criptonoticias.com",
		Category:   "general",
		Language:   "es",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"spanish", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "beincrypto_es",
		Name:       "BeInCrypto Espanol",
		RSSURL:     "https://es.beincrypto.com/feed/",
		WebsiteURL: "https://es.beincrypto.com",
		Category:   "general",
		Language:   "es",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"spanish", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "bitcobie",
		Name:       "Bitcobie",
		RSSURL:     "https://bitcobie.com/feed/",
		WebsiteURL: "https://bitcobie.com",
		Category:   "bitcoin",
		Language:   "es",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"spanish", "bitcoin", "education"},
		IsEnabled:  true,
	},
	{
		Key:        "observatorioblockchain",
		Name:       "Observatorio Blockchain",
		RSSURL:     "https://observatorioblockchain.com/feed/",
		WebsiteURL: "https://observatorioblockchain.com",
		Category:   "general",
		Language:   "es",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"spanish", "spain", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptonews_es",
		Name:       "Cryptonews Espanol",
		RSSURL:     "https://es.cryptonews.com/news/feed/",
		WebsiteURL: "https://es.cryptonews.com",
		Category:   "general",
		Language:   "es",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"spanish", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// PORTUGUESE (pt) - Brazil & Portugal
	// ============================================================================
	{
		Key:        "cointelegraph_br",
		Name:       "Cointelegraph Brasil",
		RSSURL:     "https://br.cointelegraph.com/rss",
		WebsiteURL: "https://br.cointelegraph.com",
		Category:   "general",
		Language:   "pt",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"portuguese", "brazil", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "livecoins",
		Name:       "Livecoins",
		RSSURL:     "https://livecoins.com.br/feed/",
		WebsiteURL: "https://livecoins.com.br",
		Category:   "general",
		Language:   "pt",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"portuguese", "brazil", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "portaldobitcoin",
		Name:       "Portal do Bitcoin",
		RSSURL:     "https://portaldobitcoin.uol.com.br/feed/",
		WebsiteURL: "https://portaldobitcoin.uol.com.br",
		Category:   "general",
		Language:   "pt",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"portuguese", "brazil", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "beincrypto_br",
		Name:       "BeInCrypto Brasil",
		RSSURL:     "https://br.beincrypto.com/feed/",
		WebsiteURL: "https://br.beincrypto.com",
		Category:   "general",
		Language:   "pt",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"portuguese", "brazil", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "criptofacil",
		Name:       "CriptoFacil",
		RSSURL:     "https://www.criptofacil.com/feed/",
		WebsiteURL: "https://www.criptofacil.com",
		Category:   "general",
		Language:   "pt",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"portuguese", "brazil", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "bitcoinheiro",
		Name:       "Bitcoinheiro",
		RSSURL:     "https://bitcoinheiro.com/feed/",
		WebsiteURL: "https://bitcoinheiro.com",
		Category:   "bitcoin",
		Language:   "pt",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"portuguese", "brazil", "bitcoin"},
		IsEnabled:  true,
	},
	{
		Key:        "webitcoin",
		Name:       "WeBitcoin",
		RSSURL:     "https://webitcoin.com.br/feed/",
		WebsiteURL: "https://webitcoin.com.br",
		Category:   "general",
		Language:   "pt",
		Region:     "latam",
		IsPremium:  false,
		Tags:       []string{"portuguese", "brazil", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// GERMAN (de) - Germany, Austria, Switzerland
	// ============================================================================
	{
		Key:        "btc_echo",
		Name:       "BTC-ECHO",
		RSSURL:     "https://www.btc-echo.de/feed/",
		WebsiteURL: "https://www.btc-echo.de",
		Category:   "general",
		Language:   "de",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"german", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "cointelegraph_de",
		Name:       "Cointelegraph Deutsch",
		RSSURL:     "https://de.cointelegraph.com/rss",
		WebsiteURL: "https://de.cointelegraph.com",
		Category:   "general",
		Language:   "de",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"german", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "bitcoinblog",
		Name:       "BitcoinBlog.de",
		RSSURL:     "https://bitcoinblog.de/feed/",
		WebsiteURL: "https://bitcoinblog.de",
		Category:   "bitcoin",
		Language:   "de",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"german", "bitcoin"},
		IsEnabled:  true,
	},
	{
		Key:        "blocktrainer",
		Name:       "Blocktrainer",
		RSSURL:     "https://www.blocktrainer.de/feed/",
		WebsiteURL: "https://www.blocktrainer.de",
		Category:   "bitcoin",
		Language:   "de",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"german", "bitcoin", "education"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptomonday",
		Name:       "CryptoMonday",
		RSSURL:     "https://cryptomonday.de/feed/",
		WebsiteURL: "https://cryptomonday.de",
		Category:   "general",
		Language:   "de",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"german", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// FRENCH (fr) - France, Belgium, Switzerland
	// ============================================================================
	{
		Key:        "journalducoin",
		Name:       "Journal du Coin",
		RSSURL:     "https://journalducoin.com/feed/",
		WebsiteURL: "https://journalducoin.com",
		Category:   "general",
		Language:   "fr",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"french", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "cointelegraph_fr",
		Name:       "Cointelegraph France",
		RSSURL:     "https://fr.cointelegraph.com/rss",
		WebsiteURL: "https://fr.cointelegraph.com",
		Category:   "general",
		Language:   "fr",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"french", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptoast",
		Name:       "Cryptoast",
		RSSURL:     "https://cryptoast.fr/feed/",
		WebsiteURL: "https://cryptoast.fr",
		Category:   "general",
		Language:   "fr",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"french", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "coinacademy",
		Name:       "CoinAcademy",
		RSSURL:     "https://coinacademy.fr/feed/",
		WebsiteURL: "https://coinacademy.fr",
		Category:   "general",
		Language:   "fr",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"french", "education"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptonaute",
		Name:       "Cryptonaute",
		RSSURL:     "https://cryptonaute.fr/feed/",
		WebsiteURL: "https://cryptonaute.fr",
		Category:   "general",
		Language:   "fr",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"french", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// RUSSIAN (ru) - Russia & CIS
	// ============================================================================
	{
		Key:        "cointelegraph_ru",
		Name:       "Cointelegraph Russia",
		RSSURL:     "https://ru.cointelegraph.com/rss",
		WebsiteURL: "https://ru.cointelegraph.com",
		Category:   "general",
		Language:   "ru",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"russian", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "forklog",
		Name:       "ForkLog",
		RSSURL:     "https://forklog.com/feed/",
		WebsiteURL: "https://forklog.com",
		Category:   "general",
		Language:   "ru",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"russian", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "bits_media",
		Name:       "Bits.Media",
		RSSURL:     "https://bits.media/rss/",
		WebsiteURL: "https://bits.media",
		Category:   "general",
		Language:   "ru",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"russian", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "coinspot",
		Name:       "CoinSpot",
		RSSURL:     "https://coinspot.io/feed/",
		WebsiteURL: "https://coinspot.io",
		Category:   "general",
		Language:   "ru",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"russian", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "beincrypto_ru",
		Name:       "BeInCrypto Russia",
		RSSURL:     "https://ru.beincrypto.com/feed/",
		WebsiteURL: "https://ru.beincrypto.com",
		Category:   "general",
		Language:   "ru",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"russian", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// TURKISH (tr) - Turkey
	// ============================================================================
	{
		Key:        "cointelegraph_tr",
		Name:       "Cointelegraph Turkiye",
		RSSURL:     "https://tr.cointelegraph.com/rss",
		WebsiteURL: "https://tr.cointelegraph.com",
		Category:   "general",
		Language:   "tr",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"turkish", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "koinmedya",
		Name:       "KoinMedya",
		RSSURL:     "https://koinmedya.com/feed/",
		WebsiteURL: "https://koinmedya.com",
		Category:   "general",
		Language:   "tr",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"turkish", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "uzmancoin",
		Name:       "UzmanCoin",
		RSSURL:     "https://uzmancoin.com/feed/",
		WebsiteURL: "https://uzmancoin.com",
		Category:   "general",
		Language:   "tr",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"turkish", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "coinotag",
		Name:       "CoinOtag",
		RSSURL:     "https://coinotag.com/feed/",
		WebsiteURL: "https://coinotag.com",
		Category:   "general",
		Language:   "tr",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"turkish", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// ITALIAN (it) - Italy
	// ============================================================================
	{
		Key:        "cointelegraph_it",
		Name:       "Cointelegraph Italia",
		RSSURL:     "https://it.cointelegraph.com/rss",
		WebsiteURL: "https://it.cointelegraph.com",
		Category:   "general",
		Language:   "it",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"italian", "news", "tier1"},
		IsEnabled:  true,
	},
	{
		Key:        "cryptonomist",
		Name:       "The Cryptonomist",
		RSSURL:     "https://cryptonomist.ch/feed/",
		WebsiteURL: "https://cryptonomist.ch",
		Category:   "general",
		Language:   "it",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"italian", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "criptovaluta_it",
		Name:       "Criptovaluta.it",
		RSSURL:     "https://www.criptovaluta.it/feed",
		WebsiteURL: "https://www.criptovaluta.it",
		Category:   "general",
		Language:   "it",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"italian", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// DUTCH (nl) - Netherlands, Belgium
	// ============================================================================
	{
		Key:        "bitcoinmagazine_nl",
		Name:       "Bitcoin Magazine NL",
		RSSURL:     "https://bitcoinmagazine.nl/feed/",
		WebsiteURL: "https://bitcoinmagazine.nl",
		Category:   "bitcoin",
		Language:   "nl",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"dutch", "bitcoin"},
		IsEnabled:  true,
	},
	{
		Key:        "crypto_insiders",
		Name:       "Crypto Insiders",
		RSSURL:     "https://www.crypto-insiders.nl/feed/",
		WebsiteURL: "https://www.crypto-insiders.nl",
		Category:   "general",
		Language:   "nl",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"dutch", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// POLISH (pl) - Poland
	// ============================================================================
	{
		Key:        "bitcoin_pl",
		Name:       "Bitcoin.pl",
		RSSURL:     "https://bitcoin.pl/feed/",
		WebsiteURL: "https://bitcoin.pl",
		Category:   "bitcoin",
		Language:   "pl",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"polish", "bitcoin"},
		IsEnabled:  true,
	},
	{
		Key:        "kryptowaluty_pl",
		Name:       "Kryptowaluty.pl",
		RSSURL:     "https://kryptowaluty.pl/feed/",
		WebsiteURL: "https://kryptowaluty.pl",
		Category:   "general",
		Language:   "pl",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"polish", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// VIETNAMESE (vi) - Vietnam
	// ============================================================================
	{
		Key:        "beincrypto_vi",
		Name:       "BeInCrypto Vietnam",
		RSSURL:     "https://vi.beincrypto.com/feed/",
		WebsiteURL: "https://vi.beincrypto.com",
		Category:   "general",
		Language:   "vi",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"vietnamese", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "tapchibitcoin",
		Name:       "Tap Chi Bitcoin",
		RSSURL:     "https://tapchibitcoin.io/feed/",
		WebsiteURL: "https://tapchibitcoin.io",
		Category:   "general",
		Language:   "vi",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"vietnamese", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "coinvn",
		Name:       "CoinVN",
		RSSURL:     "https://coinvn.com/feed/",
		WebsiteURL: "https://coinvn.com",
		Category:   "general",
		Language:   "vi",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"vietnamese", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// INDONESIAN (id) - Indonesia
	// ============================================================================
	{
		Key:        "beincrypto_id",
		Name:       "BeInCrypto Indonesia",
		RSSURL:     "https://id.beincrypto.com/feed/",
		WebsiteURL: "https://id.beincrypto.com",
		Category:   "general",
		Language:   "id",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"indonesian", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "coinvestasi",
		Name:       "Coinvestasi",
		RSSURL:     "https://coinvestasi.com/feed/",
		WebsiteURL: "https://coinvestasi.com",
		Category:   "general",
		Language:   "id",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"indonesian", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "cointelegraph_id",
		Name:       "Cointelegraph Indonesia",
		RSSURL:     "https://id.cointelegraph.com/rss",
		WebsiteURL: "https://id.cointelegraph.com",
		Category:   "general",
		Language:   "id",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"indonesian", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// THAI (th) - Thailand
	// ============================================================================
	{
		Key:        "siamblockchain",
		Name:       "Siam Blockchain",
		RSSURL:     "https://siamblockchain.com/feed/",
		WebsiteURL: "https://siamblockchain.com",
		Category:   "general",
		Language:   "th",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"thai", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "bitcoinaddict_th",
		Name:       "Bitcoin Addict Thailand",
		RSSURL:     "https://bitcoinaddict.org/feed/",
		WebsiteURL: "https://bitcoinaddict.org",
		Category:   "general",
		Language:   "th",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"thai", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// ARABIC (ar) - Middle East & North Africa
	// ============================================================================
	{
		Key:        "cointelegraph_ar",
		Name:       "Cointelegraph Arabic",
		RSSURL:     "https://ar.cointelegraph.com/rss",
		WebsiteURL: "https://ar.cointelegraph.com",
		Category:   "general",
		Language:   "ar",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"arabic", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "arabicrypto",
		Name:       "ArabiCrypto",
		RSSURL:     "https://arabicrypto.com/feed/",
		WebsiteURL: "https://arabicrypto.com",
		Category:   "general",
		Language:   "ar",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"arabic", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "beincrypto_ar",
		Name:       "BeInCrypto Arabic",
		RSSURL:     "https://ar.beincrypto.com/feed/",
		WebsiteURL: "https://ar.beincrypto.com",
		Category:   "general",
		Language:   "ar",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"arabic", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// HINDI (hi) - India
	// ============================================================================
	{
		Key:        "coinswitch_hi",
		Name:       "CoinSwitch Hindi",
		RSSURL:     "https://coinswitch.co/blog/hi/feed/",
		WebsiteURL: "https://coinswitch.co",
		Category:   "general",
		Language:   "hi",
		Region:     "asia",
		IsPremium:  false,
		Tags:       []string{"hindi", "india"},
		IsEnabled:  true,
	},

	// ============================================================================
	// PERSIAN (fa) - Iran
	// ============================================================================
	{
		Key:        "arzdigital",
		Name:       "Arz Digital",
		RSSURL:     "https://arzdigital.com/feed/",
		WebsiteURL: "https://arzdigital.com",
		Category:   "general",
		Language:   "fa",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"persian", "iran", "news"},
		IsEnabled:  true,
	},
	{
		Key:        "mihanblockchain",
		Name:       "Mihan Blockchain",
		RSSURL:     "https://mihanblockchain.com/feed/",
		WebsiteURL: "https://mihanblockchain.com",
		Category:   "general",
		Language:   "fa",
		Region:     "global",
		IsPremium:  false,
		Tags:       []string{"persian", "iran", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// GREEK (el) - Greece
	// ============================================================================
	{
		Key:        "cryptonews_gr",
		Name:       "CryptoNews Greece",
		RSSURL:     "https://el.cryptonews.com/news/feed/",
		WebsiteURL: "https://el.cryptonews.com",
		Category:   "general",
		Language:   "el",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"greek", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// CZECH (cs) - Czech Republic
	// ============================================================================
	{
		Key:        "cryptomag_cz",
		Name:       "Cryptomag.cz",
		RSSURL:     "https://cryptomag.cz/feed/",
		WebsiteURL: "https://cryptomag.cz",
		Category:   "general",
		Language:   "cs",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"czech", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// ROMANIAN (ro) - Romania
	// ============================================================================
	{
		Key:        "bitcoinro",
		Name:       "Bitcoin Romania",
		RSSURL:     "https://bitcoin.ro/feed/",
		WebsiteURL: "https://bitcoin.ro",
		Category:   "general",
		Language:   "ro",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"romanian", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// UKRAINIAN (uk) - Ukraine
	// ============================================================================
	{
		Key:        "incrypted",
		Name:       "Incrypted",
		RSSURL:     "https://incrypted.com/feed/",
		WebsiteURL: "https://incrypted.com",
		Category:   "general",
		Language:   "uk",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"ukrainian", "news"},
		IsEnabled:  true,
	},

	// ============================================================================
	// SWEDISH (sv) - Sweden
	// ============================================================================
	{
		Key:        "trijo_se",
		Name:       "Trijo News",
		RSSURL:     "https://trijo.co/nyheter/feed/",
		WebsiteURL: "https://trijo.co",
		Category:   "general",
		Language:   "sv",
		Region:     "europe",
		IsPremium:  false,
		Tags:       []string{"swedish", "news"},
		IsEnabled:  true,
	},
}
